import type { Metadata } from "next";
import { Raleway, Fira_Code } from "next/font/google";
import "../scss/index.scss";

const raleway = Raleway({
  subsets: ["latin"],
  variable: "--raleway",
  weight: ["300", "400", "500", "600", "700"],
});
const firaCode = Fira_Code({
  subsets: ["latin"],
  variable: "--fira-code",
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Nitin Rajput",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${raleway.variable} ${firaCode.variable}`}>
      <body>{children}</body>
    </html>
  );
}
