import type { Metadata } from "next";
import { Raleway, Fira_Code } from "next/font/google";
import "../scss/index.scss";

const raleway = Raleway({ subsets: ["latin"] });
const firaCode = Fira_Code({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "Nitin Rajput",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${raleway.className} ${firaCode.className}`}>
        {children}
      </body>
    </html>
  );
}
